CREATE TABLE IF NOT EXISTS `nomina` (
  `id` int(11) AUTO_INCREMENT PRIMARY KEY,
  `fecha_inicio` TEXT(250) NOT NULL,
  `fecha_final` TEXT(250) NOT NULL,
  `token` TEXT(250) NOT NULL,
  `codigo` TEXT(250) NOT NULL,
  `nombre` TEXT(250) NOT NULL,
  `cargo` TEXT(250) NOT NULL,
  `sueldo` TEXT(250) NOT NULL,
  `comision` TEXT(250) NOT NULL,
  `hora_extra` TEXT(250) NOT NULL,
  `total_ingreso` TEXT(250) NOT NULL,
  `ingreso_sdss` TEXT(250) NOT NULL,
  `sf_salud` TEXT(250) NOT NULL,
  `svejez_discap` TEXT(250) NOT NULL,
  `desc_percapita` TEXT(250) NOT NULL,
  `base_isr` TEXT(250) NOT NULL,
  `imp_sobre_renta` TEXT(250) NOT NULL,
  `prestamos` TEXT(250) NOT NULL,
  `avance_sueldo` TEXT(250) NOT NULL,
  `total_deducciones` TEXT(250) NOT NULL,
  `total_neto_pagar` TEXT(250) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `usuario` text(250) COLLATE utf8_spanish_ci NOT NULL
);