import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const cajaSource = readFileSync(resolve(process.cwd(), 'src/renderer/src/views/Caja/Caja.vue'), 'utf8')
const printerSource = readFileSync(resolve(process.cwd(), 'src/renderer/src/printer/cuadreCompleto.js'), 'utf8')
const mainSource = readFileSync(resolve(process.cwd(), 'src/main/index.js'), 'utf8')

describe('Impresión del cuadre de caja', () => {
  it('muestra el número de facturas del turno en los datos del usuario', () => {
    expect(cajaSource).toContain('Facturas del turno')
    expect(cajaSource).toContain('{{ cantidadFacturasTurno }}')
    expect(cajaSource).toContain('const cantidadFacturasTurno = ref(0)')
    expect(cajaSource).toContain('cantidadFacturasTurno.value = facturasTurno.length')
    expect(cajaSource).toContain('await fetchAndSetupDatosdelDia();')
    expect(cajaSource).toContain('label="Resumen del cuadre"')
    expect(cajaSource).toContain('@click="abrirResumenCuadre"')
    expect(cajaSource).toContain('v-model:visible="visibleResumenCuadre"')
    expect(cajaSource).toContain('const diferenciaCuadre = computed')
    expect(cajaSource).toContain('const resumenCuadreDenominaciones = computed')
    expect(cajaSource).toContain('La caja no se cerrará hasta presionar “Cuadrar Caja”')
    expect(cajaSource).toContain('Cálculo del efectivo registrado')
    expect(cajaSource).toContain('Información del turno')
    expect(cajaSource).toContain('Facturas realizadas')
    expect(cajaSource).toContain('Abonos CxC en efectivo')
    expect(cajaSource).toContain('const resumenCuadreEfectivo = computed')
    expect(cajaSource).toContain('TOTAL GASTOS')
    expect(cajaSource).toContain(':modelValue="Number(datosDelDia.gastos || 0).toFixed(2)"')
    expect(cajaSource).toContain('TOTAL VENTAS')
    expect(cajaSource).toContain(':modelValue="Number(datosDelDia.venta || 0).toFixed(2)"')
    expect(cajaSource).toContain('ABONOS CXC')
    expect(cajaSource).toContain(':modelValue="Number(datosDelDia.abono || 0).toFixed(2)"')
    expect(cajaSource).toContain('ABONOS DE TALLER')
    expect(cajaSource).toContain(':modelValue="Number(datosDelDia.taller || 0).toFixed(2)"')
    expect(cajaSource).toContain('.contar-dinero-resumen-card .col-span-6')
    expect(cajaSource).toContain('max-height: calc(100vh - 12rem)')
    expect(cajaSource).toContain('overflow-y: auto')
    expect(cajaSource).toContain('for (const actualizar of [fetchAndSetupDatosdelDia, actualizarCantidadFacturasTurno])')
    expect(cajaSource).toContain('visibleResumenCuadre.value = true')
    expect(cajaSource).toContain('La vista previa debe seguir disponible con los valores ya cargados.')
    expect(cajaSource).not.toContain("detail: 'No se pudo actualizar la información del cuadre.'")
    expect(cajaSource).toContain("const fechaFinN = nfecha('timestamp');")
    expect(cajaSource).toContain('return !turnoMovimiento || turnoMovimiento === normalizar(turnoActual);')
    expect(cajaSource).toContain('const cantidadGastos = gastosTurno')
    expect(cajaSource).toContain('gastosEfectivo: cantidadGastoEfectivo')
    expect(cajaSource).toContain('totalEfectivo + cantidadInicio - gastoEfectivo')
    expect(cajaSource).not.toContain("peticionesFetchOffline('getDataAsArray', 'gastos')")
    expect(cajaSource).not.toContain('copiaResponse.gastos = gastosCompletos')
    expect(cajaSource).toContain('gastos: gastosTurno')
    expect(cajaSource).toContain('const gastosTurno = asArray(copiaResponse.gastos)')
    expect(cajaSource).toContain('// datosVentasPorRango2 ya devuelve los gastos comprendidos exactamente')
    expect(cajaSource).toContain('const normalizarMovimientos = (valor, campo) =>')
    expect(cajaSource).toContain("normalizarMovimientos(factura.pagos, 'cuentas_cobrar.pagos')")
    expect(cajaSource).toContain("normalizarMovimientos(factura.abono, 'taller.abono')")
    expect(cajaSource).toContain('jsonData.gastos = asArray(gastosArray.value);')
    expect(cajaSource).toContain('if (turnoActual && turnoMovimiento === normalizar(turnoActual)) return true;')
    expect(cajaSource).toContain("camposGastos.value.metodo = String(camposGastos.value.metodo || 'EFECTIVO').trim().toUpperCase()")
    expect(cajaSource).toContain('token: cajaActual.turno')
    expect(cajaSource).toContain("window.localStorage.setItem('usuarioLocal', JSON.stringify([usuarioActualizado]))")
  })

  it('envía las colecciones recién consultadas y nunca valores undefined', () => {
    expect(cajaSource).toContain('const datosCajaImpresion = {')
    expect(cajaSource).toContain('facturas: facturasFiltradas')
    expect(cajaSource).toContain('nDatosEmpresa.datoscaja = datosCajaImpresion')
  })

  it('normaliza todas las tablas antes de ejecutar filter', () => {
    expect(printerSource).toContain('const datosCajaRecibidos = datosLocalStorage.datoscaja || {}')
    expect(printerSource).toContain('facturas: asArray(datosCajaRecibidos.facturas)')
    expect(printerSource).toContain('cuentas_cobrar: asArray(datosCajaRecibidos.cuentas_cobrar)')
    expect(printerSource).toContain("jsonData['cuentas_cobrar']")
    expect(printerSource).not.toContain('const responseCxC = await peticionesFetch')
  })

  it('espera el resultado real y propaga errores de impresión a Caja', () => {
    expect(printerSource).toContain('return await new Promise((resolve, reject) => {')
    expect(printerSource).toContain('resolve({ printed: true')
    expect(mainSource).toContain('return { ok: true, result }')
    expect(mainSource).toContain("return { ok: false, error: error?.message || String(error) }")
    expect(cajaSource).toContain('if (!resultadoImpresion?.ok)')
    expect(cajaSource).toContain("summary: 'No se pudo imprimir el cuadre'")
  })
})
