CREATE TABLE IF NOT EXISTS `cuentas_cobrar` (
  `id` int(11) AUTO_INCREMENT PRIMARY KEY,
  `no_emision` TEXT(250) NOT NULL,
  `no_factura` TEXT(250) NOT NULL,
  `cod_cliente` TEXT(250) NOT NULL,
  `nombre_cliente` TEXT(250) NOT NULL,
  `cedula_cliente` TEXT(250) NOT NULL,
  `telefono_cliente` TEXT(250) NOT NULL,
  `whatsapp_cliente` TEXT(250) NOT NULL,
  `email_cliente` TEXT(250) NOT NULL,
  `direccion_cliente` TEXT(250) NOT NULL,
  `rnc_cliente` TEXT(250) NOT NULL,
  `nombrecomercial_cliente` TEXT(250) NOT NULL,
  `fecha_emision` TEXT(250) NOT NULL,
  `monto_credito` TEXT(250) NOT NULL,
  `interes` TEXT(250) NOT NULL,
  `fecha_vencimiento` TEXT(250) NOT NULL,
  `cuotas` TEXT(250) NOT NULL,
  `saldo` TEXT(250) NOT NULL,
  `fecha_pago` TEXT(250) NOT NULL,
  `pagos` TEXT(250) NOT NULL,
  `estatus` TEXT(250) NOT NULL,
  `hora` TEXT(250) NOT NULL,
  `vendedor` TEXT(250) NOT NULL,
  `delivey` TEXT(250) NOT NULL,
  `nota` TEXT(250) NOT NULL,
  `updated_at` TEXT(250) NOT NULL,
  `created_at` TEXT(250) NOT NULL,
  `usuario` text(250) COLLATE utf8_spanish_ci NOT NULL
);