CREATE TABLE IF NOT EXISTS `cotizacion` (
  `id` int(11) AUTO_INCREMENT PRIMARY KEY,
  `no_cotizacion` TEXT(250) NOT NULL,
  `cod_cliente` TEXT(250) NOT NULL,
  `nombre_cliente` TEXT(250) NOT NULL,
  `telefono_cliente` TEXT(250) NOT NULL,
  `whatsapp_cliente` TEXT(250) NOT NULL,
  `email_cliente` TEXT(250) NOT NULL,
  `direccion_cliente` TEXT(250) NOT NULL,
  `rnc_cliente` TEXT(250) NOT NULL,
  `nombre_comercial` TEXT(250) NOT NULL,
  `productos` TEXT(250) NOT NULL,
  `vendedor` TEXT(250) NOT NULL,
  `metodo_pago` TEXT(250) NOT NULL,
  `fecha_emision` TEXT(250) NOT NULL,
  `impuesto` TEXT(250) NOT NULL,
  `descuento` TEXT(250) NOT NULL,
  `subtotal` TEXT(250) NOT NULL,
  `total` TEXT(250) NOT NULL,
  `estado_cotizacion` TEXT(250) NOT NULL,
  `no_factura` TEXT(250) NOT NULL,
  `fecha_cambio` TEXT(250) NOT NULL,
  `entidad_financiera` TEXT(250) NOT NULL,
  `vencimiento` TEXT(250) NOT NULL,
  `nota` TEXT(250) NOT NULL,
  `year` TEXT(250) NOT NULL,
  `mes` TEXT(250) NOT NULL,
  `hora` TEXT(250) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `usuario` text(250) COLLATE utf8_spanish_ci NOT NULL
);