CREATE TABLE IF NOT EXISTS `compras` (
  `id` int(11) AUTO_INCREMENT PRIMARY KEY,
  `proveedor` TEXT(250) NOT NULL,
  `rnc_proveedor` TEXT(250) NOT NULL,
  `fecha` TEXT(250) NOT NULL,
  `no_factura` TEXT(250) NOT NULL,
  `ncf_proveedor` TEXT(250) NOT NULL,
  `productos` TEXT(250) NOT NULL,
  `estado` TEXT(250) NOT NULL,
  `subtotal` TEXT(250) NOT NULL,
  `descuento` TEXT(250) NOT NULL,
  `impuesto` TEXT(250) NOT NULL,
  `total` TEXT(250) NOT NULL,
  `abono` TEXT(250) NOT NULL,
  `saldo` TEXT(250) NOT NULL,
  `nota` TEXT(250) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `usuario` text(250) COLLATE utf8_spanish_ci NOT NULL
);