CREATE TABLE IF NOT EXISTS `facturas` (
  `id` int(11) AUTO_INCREMENT PRIMARY KEY,
  `no_factura` TEXT(250) NOT NULL,
  `tipo_factura` TEXT(250) NOT NULL,
  `comprobante` TEXT(250) NOT NULL,
  `cod_cliente` TEXT(250) NOT NULL,
  `nombre_cliente` TEXT(250) NOT NULL,
  `telefono_cliente` TEXT(250) NOT NULL,
  `productos` TEXT(250) NOT NULL,
  `vendedor` TEXT(250) NOT NULL,
  `metodo_pago` TEXT(250) NOT NULL,
  `tarjeta` TEXT(250) NOT NULL,
  `transferencia` TEXT(250) NOT NULL,
  `efectivo` TEXT(250) NOT NULL,
  `canal_venta` TEXT(250) NOT NULL,
  `fecha_emision` TEXT(250) NOT NULL,
  `impuesto` TEXT(250) NOT NULL,
  `descuento` TEXT(250) NOT NULL,
  `subtotal` TEXT(250) NOT NULL,
  `total` TEXT(250) NOT NULL,
  `ganancia` TEXT(250) NOT NULL,
  `financiera` TEXT(250) NOT NULL,
  `estado_factura` TEXT(250) NOT NULL,
  `fecha_estado` TEXT(250) NOT NULL,
  `mes` TEXT(250) NOT NULL,
  `year` TEXT(250) NOT NULL,
  `hora` TEXT(250) NOT NULL,
  `otro` TEXT(250) NOT NULL,
  `nota` TEXT(250) NOT NULL,
  `cajero` TEXT(250) NOT NULL,
  `token` TEXT(250) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `usuario` text(250) COLLATE utf8_spanish_ci NOT NULL
);