CREATE TABLE IF NOT EXISTS `clientes` (
  `id` int(11) AUTO_INCREMENT PRIMARY KEY,
  `nombre` TEXT(250) NOT NULL,
  `cedula` TEXT(250) NOT NULL,
  `telefono` TEXT(250) NOT NULL,
  `email` TEXT(250) NOT NULL,
  `password` TEXT(250) NOT NULL,
  `direccion` TEXT(250) NOT NULL,
  `whatsapp` TEXT(250) NOT NULL,
  `genero` TEXT(250) NOT NULL,
  `estado_civil` TEXT(250) NOT NULL,
  `apodo` TEXT(250) NOT NULL,
  `fecha_nacimiento` TEXT(250) NOT NULL,
  `edad` TEXT(250) NOT NULL,
  `precio_fijado` TEXT(250) NOT NULL,
  `empresa` TEXT(250) NOT NULL,
  `cargo` TEXT(250) NOT NULL,
  `telefono_empresa` TEXT(250) NOT NULL,
  `direccion_empresa` TEXT(250) NOT NULL,
  `codigo` TEXT(250) NOT NULL,
  `n_comercial` TEXT(250) NOT NULL,
  `rnc` TEXT(250) NOT NULL,
  `imagen` TEXT(250) NOT NULL,
  `activo` TEXT(250) NOT NULL,
  `zona` TEXT(250) NOT NULL,
  `delivery` TEXT(250) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `usuario` text(250) COLLATE utf8_spanish_ci NOT NULL
);
