CREATE TABLE IF NOT EXISTS `pin` (
  `id` int(11) AUTO_INCREMENT PRIMARY KEY,
  `usuario` TEXT(250) NOT NULL,
  `pin` TEXT(250) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);