CREATE TABLE IF NOT EXISTS `registrocaja` (
  `id` int(11) AUTO_INCREMENT PRIMARY KEY,
  `ganancias` TEXT(250) NOT NULL,
  `taller` TEXT(250) NOT NULL,
  `cuentas_cobrar` TEXT(250) NOT NULL,
  `cuentas_pagar` TEXT(250) NOT NULL,
  `propinas` TEXT(250) NOT NULL,
  `turno` TEXT(250) NOT NULL,
  `nombre` TEXT(250) NOT NULL,
  `username` TEXT(250) NOT NULL,
  `fecha` TEXT(250) NOT NULL,
  `hora_inicio` TEXT(250) NOT NULL,
  `hora_cierre` TEXT(250) NOT NULL,
  `cant_inicio` TEXT(250) NOT NULL,
  `ventas` TEXT(250) NOT NULL,
  `efectivo` TEXT(250) NOT NULL,
  `tarjeta` TEXT(250) NOT NULL,
  `transferencia` TEXT(250) NOT NULL,
  `cheque` TEXT(250) NOT NULL,
  `entradas` TEXT(250) NOT NULL,
  `inversiones` TEXT(250) NOT NULL,
  `gastos` TEXT(250) NOT NULL,
  `devoluciones` TEXT(250) NOT NULL,
  `estado` TEXT(250) NOT NULL,
  `abono` TEXT(250) NOT NULL,
  `otro` TEXT(250) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `usuario` text(250) COLLATE utf8_spanish_ci NOT NULL
);